# NOTE: update this with your service name
service: games-app-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /games
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create.main
    events:
      - http:
          path: games
          method: post
          cors: true
          authorizer: 
            arn: arn:aws:cognito-idp:us-east-1:520335913573:userpool/us-east-1_zUzCDnLDQ
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /games/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: games/{id}
          method: get
          cors: true
          authorizer: 
            arn: arn:aws:cognito-idp:us-east-1:520335913573:userpool/us-east-1_zUzCDnLDQ

  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /games
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: games
          method: get
          cors: true
          authorizer: 
            arn: arn:aws:cognito-idp:us-east-1:520335913573:userpool/us-east-1_zUzCDnLDQ
  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /games/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: games/{id}
          method: put
          cors: true
          authorizer: 
            arn: arn:aws:cognito-idp:us-east-1:520335913573:userpool/us-east-1_zUzCDnLDQ
  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /games/{id}
    # - method: DELETE request
    handler: delete.main
    events:
      - http:
          path: games/{id}
          method: delete
          cors: true
          authorizer: 
            arn: arn:aws:cognito-idp:us-east-1:520335913573:userpool/us-east-1_zUzCDnLDQ